# Generated by Django 4.1 on 2023-02-06 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_alter_client_options_alter_orderitem_modified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 12, 16, 48, 82760)),
        ),
    ]
