# Generated by Django 4.1 on 2023-02-06 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_client_options_alter_item_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 12, 25, 24, 781253)),
        ),
    ]
