# Generated by Django 4.1 on 2023-02-06 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0006_description_alter_orderitem_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 14, 12, 18, 81137)),
        ),
        migrations.AddField(
            model_name='description',
            name='desc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='myapp1.projectdescription'),
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='myapp1.projecttitle'),
        ),
    ]
