# Generated by Django 4.1 on 2023-02-06 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_projectdescription_projecttitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectdescription',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='description',
            name='desc',
        ),
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.ManyToManyField(to='myapp1.projectdescription'),
        ),
        migrations.RemoveField(
            model_name='description',
            name='title',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 14, 18, 31, 225867)),
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.ManyToManyField(to='myapp1.projecttitle'),
        ),
    ]
