# Generated by Django 4.1 on 2023-02-06 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0009_alter_orderitem_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='description',
            old_name='title',
            new_name='titles',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 14, 45, 48, 998503)),
        ),
    ]
