# Generated by Django 4.1 on 2023-02-07 02:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0010_rename_description_description_descriptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='description',
            name='titles',
        ),
        migrations.AddField(
            model_name='description',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 2, 7, 2, 33, 16, 35874, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 21, 32, 55, 325858)),
        ),
        migrations.DeleteModel(
            name='ProjectDescription',
        ),
        migrations.DeleteModel(
            name='ProjectTitle',
        ),
    ]
