# Generated by Django 4.1 on 2023-02-07 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_remove_description_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 6, 21, 33, 39, 869747)),
        ),
    ]
