# Generated by Django 4.1 on 2023-02-27 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_alter_orderitem_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 0, 44, 43, 481450)),
        ),
    ]
