# Generated by Django 4.1 on 2023-03-07 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0013_alter_orderitem_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='interested',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 7, 13, 27, 38, 683744)),
        ),
    ]
